spring:
  application:
    name: order-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order_db
      repositories:
        type: auto
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka
  instance:
    hostname: localhost
server:
  port: 2020
